/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scheduler;

import java.awt.Color;
import java.awt.Component;
import java.awt.print.PrinterException;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.border.MatteBorder;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ayomitunde
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    static final String[] _days = {"Sunday", "Monday", "Tuesday", "Wednesday", "Thursday",
        "Friday", "Saturday"};
    static final String[] _dept = {"Staff", "IT", "Services", "Marketing", "Human Resources", "Financial", "Purchasing", "Sales", "Inventory", "Licenses", "Operational", "Admin"};
    static final String[] _upEvents = {"Upcoming Events"};
    static int _realYear, _realMonth, _realDay, _currentYear, _currentMonth;
    GregorianCalendar _calendar;
    static DefaultTableModel _CalendarTableModel = new DefaultTableModel(_days, 6);
    static DefaultTableModel _upcomingEventsModel = new DefaultTableModel(_upEvents, 3);
    final int _CALENDAR_HEIGHT = 63;
    static ArrayList<Event> _allEvents = new ArrayList<>();
    static HashMap<User, ArrayList> _userInfo = new HashMap<>();
    static String _eventday;
    static User _currentUser;
    DateFormat _df = new SimpleDateFormat("M/dd/yyyy");
    Date _currentDate = new Date();
    static boolean _logged = false;
    
    public GUI() throws IOException {
        this._calendar = new GregorianCalendar();
        _realDay = _calendar.get(GregorianCalendar.DAY_OF_MONTH);
        _realMonth = _calendar.get(GregorianCalendar.MONTH);
        _realYear = _calendar.get(GregorianCalendar.YEAR);
        _currentMonth = _realMonth;
        _currentYear = _realYear;
        initComponents();
        set();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem4 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jDialog1 = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        editUser_Box = new javax.swing.JDialog();
        txtEditUser_Username = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtEditUser_Pwd = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        txtEditUser_Pwd2 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        tglEditUser_Admin = new javax.swing.JToggleButton();
        btnEditUser_Cancel = new javax.swing.JButton();
        btnEditUser_Save = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtEditUser_Email = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        pnlBackground = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCalendar = new javax.swing.JTable(){
            private static final long serialVersionUID = 1L;
            public boolean isCellEditable(int row, int column){
                return false;
            };
            public boolean getScrollableTracksViewportWidth(){
                return getPreferredSize().width < getParent().getWidth();
            }
        };
        cmbYear = new javax.swing.JComboBox<>();
        btnNext = new javax.swing.JButton();
        btnPrev = new javax.swing.JButton();
        lblMonth = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblUpcomingEvents = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        mnuExit = new javax.swing.JMenuItem();
        mnuMainEdit = new javax.swing.JMenu();
        mnuUser = new javax.swing.JMenu();
        mnuAddUser = new javax.swing.JMenuItem();
        mnuListEditUser = new javax.swing.JMenuItem();
        mnuRemoveUser = new javax.swing.JMenuItem();
        mnuEditPassword = new javax.swing.JMenuItem();
        mnuCustomizeCalendar = new javax.swing.JMenuItem();
        mnuServerLocation = new javax.swing.JMenuItem();

        jMenuItem4.setText("jMenuItem4");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jDialog1.setMinimumSize(new java.awt.Dimension(610, 300));
        jDialog1.setSize(new java.awt.Dimension(610, 300));

        jPanel3.setBackground(jPanel2.getBackground());
        jPanel3.repaint();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jPanel4.setBackground(jPanel2.getBackground());
        jPanel4.repaint();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 504, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        editUser_Box.setSize(new java.awt.Dimension(400, 300));

        txtEditUser_Username.setText(null);
        txtEditUser_Username.setMinimumSize(new java.awt.Dimension(150, 28));
        txtEditUser_Username.setSize(new java.awt.Dimension(150, 28));

        jLabel1.setText("Username: ");

        jLabel2.setText("New Password");

        txtEditUser_Pwd.setMinimumSize(new java.awt.Dimension(102, 28));
        txtEditUser_Pwd.setSize(new java.awt.Dimension(102, 28));

        jLabel3.setText("Confirm new password: ");

        txtEditUser_Pwd2.setMinimumSize(new java.awt.Dimension(102, 28));
        txtEditUser_Pwd2.setSize(new java.awt.Dimension(102, 28));

        jLabel4.setText("Edit User");

        tglEditUser_Admin.setText("Is Admin");

        btnEditUser_Cancel.setText("Cancel");
        btnEditUser_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditUser_CancelActionPerformed(evt);
            }
        });

        btnEditUser_Save.setText("Save");
        btnEditUser_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditUser_SaveActionPerformed(evt);
            }
        });

        jLabel5.setText("Email:");

        txtEditUser_Email.setText(null);

        javax.swing.GroupLayout editUser_BoxLayout = new javax.swing.GroupLayout(editUser_Box.getContentPane());
        editUser_Box.getContentPane().setLayout(editUser_BoxLayout);
        editUser_BoxLayout.setHorizontalGroup(
            editUser_BoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editUser_BoxLayout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jLabel4)
                .addContainerGap(183, Short.MAX_VALUE))
            .addGroup(editUser_BoxLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btnEditUser_Cancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEditUser_Save)
                .addGap(34, 34, 34))
            .addGroup(editUser_BoxLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(editUser_BoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editUser_BoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editUser_BoxLayout.createSequentialGroup()
                        .addComponent(txtEditUser_Email)
                        .addContainerGap())
                    .addGroup(editUser_BoxLayout.createSequentialGroup()
                        .addGroup(editUser_BoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(editUser_BoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtEditUser_Pwd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtEditUser_Pwd2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtEditUser_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editUser_BoxLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tglEditUser_Admin)
                .addGap(146, 146, 146))
        );
        editUser_BoxLayout.setVerticalGroup(
            editUser_BoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editUser_BoxLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(editUser_BoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEditUser_Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(8, 8, 8)
                .addGroup(editUser_BoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtEditUser_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editUser_BoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtEditUser_Pwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editUser_BoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtEditUser_Pwd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tglEditUser_Admin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(editUser_BoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditUser_Cancel)
                    .addComponent(btnEditUser_Save))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlBackground.setBackground(new java.awt.Color(204, 255, 204));
        pnlBackground.setForeground(new java.awt.Color(51, 51, 51));

        jButton1.setBackground(new java.awt.Color(102, 204, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Create Event");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnLogout.setText("Log Out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        tblCalendar.setModel(_CalendarTableModel);
        tblCalendar.setRowHeight(_CALENDAR_HEIGHT);
        tblCalendar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCalendarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCalendar);

        cmbYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));
        cmbYear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbYearMouseClicked(evt);
            }
        });
        cmbYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbYearActionPerformed(evt);
            }
        });

        btnNext.setText(">>");
        btnNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNextMouseClicked(evt);
            }
        });

        btnPrev.setText("<<");
        btnPrev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPrevMouseClicked(evt);
            }
        });
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        lblMonth.setText("jLabel1");

        javax.swing.GroupLayout pnlBackgroundLayout = new javax.swing.GroupLayout(pnlBackground);
        pnlBackground.setLayout(pnlBackgroundLayout);
        pnlBackgroundLayout.setHorizontalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLogout)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cmbYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundLayout.createSequentialGroup()
                        .addComponent(btnPrev)
                        .addGap(417, 417, 417)
                        .addComponent(lblMonth, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                        .addGap(413, 413, 413)
                        .addComponent(btnNext)
                        .addContainerGap())))
        );
        pnlBackgroundLayout.setVerticalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogout)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrev)
                    .addComponent(btnNext)
                    .addComponent(lblMonth))
                .addGap(3, 3, 3)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
        );

        jPanel1.add(pnlBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 0, 1050, 600));

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        tblUpcomingEvents.setModel(_upcomingEventsModel);
        jScrollPane3.setViewportView(tblUpcomingEvents);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 472, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 600));

        jMenu1.setText("File");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Print Calendar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        mnuExit.setText("Exit");
        mnuExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuExitMouseClicked(evt);
            }
        });
        mnuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExitActionPerformed(evt);
            }
        });
        jMenu1.add(mnuExit);

        jMenuBar1.add(jMenu1);

        mnuMainEdit.setText("Edit");

        mnuUser.setText("User");
        mnuUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuUserActionPerformed(evt);
            }
        });

        mnuAddUser.setText("Add User");
        mnuAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAddUserActionPerformed(evt);
            }
        });
        mnuUser.add(mnuAddUser);

        mnuListEditUser.setText("List/Edit Users");
        mnuListEditUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuListEditUserActionPerformed(evt);
            }
        });
        mnuUser.add(mnuListEditUser);

        mnuRemoveUser.setText("Remove User");
        mnuRemoveUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRemoveUserActionPerformed(evt);
            }
        });
        mnuUser.add(mnuRemoveUser);

        mnuEditPassword.setText("Edit Password");
        mnuEditPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEditPasswordActionPerformed(evt);
            }
        });
        mnuUser.add(mnuEditPassword);

        mnuCustomizeCalendar.setText("Customize Calendar");
        mnuCustomizeCalendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCustomizeCalendarActionPerformed(evt);
            }
        });
        mnuUser.add(mnuCustomizeCalendar);

        mnuMainEdit.add(mnuUser);

        mnuServerLocation.setText("Server Location");
        mnuServerLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuServerLocationActionPerformed(evt);
            }
        });
        mnuMainEdit.add(mnuServerLocation);

        jMenuBar1.add(mnuMainEdit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuExitMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuExitMouseClicked

    private void mnuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExitActionPerformed
        // TODO add your handling code here:
        Serialize.save(Serialize.fileLocation); // change this to your desktop just for testing
        System.exit(0);
    }//GEN-LAST:event_mnuExitActionPerformed
    

    private void mnuAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAddUserActionPerformed
        this.setVisible(false);
        AddUsers.run();

    }//GEN-LAST:event_mnuAddUserActionPerformed
    
    private void set() {
        tblCalendar.getTableHeader().setResizingAllowed(false);
        tblCalendar.getTableHeader().setReorderingAllowed(false);
        tblCalendar.setColumnSelectionAllowed(true);
        tblCalendar.setRowSelectionAllowed(true);
        tblCalendar.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblCalendar.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        
        tblUpcomingEvents.getTableHeader().setResizingAllowed(false);
        tblUpcomingEvents.getTableHeader().setReorderingAllowed(false);
        tblUpcomingEvents.setColumnSelectionAllowed(true);
        tblUpcomingEvents.setRowSelectionAllowed(true);
        tblUpcomingEvents.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        for (int i = _realYear - 100; i <= _realYear + 100; i++) {
            cmbYear.addItem(String.valueOf(i));
        }
        refreshCalendar(_realMonth, _realYear);
        if (_logged == true) {
            for (Iterator<User> u = _userInfo.keySet().iterator(); u.hasNext();) {
                _currentUser = u.next();
                if (_currentUser.getLogged()) {
                    if (_currentUser.isAdmin() == false) {
                        hideNonAdmin();
                        if (_currentUser.getCustomColor() != null) {
                            pnlBackground.setBackground(_currentUser.getCustomColor());
                        }
                    } else {
                        
                    }
                }
            }
        }
        
        String currentDate = _df.format(_currentDate);
        System.err.println(currentDate);
        int j = 0;
        if (_currentUser != null) { // null check should be removed later
            ArrayList<Event> currentuserEvents = _userInfo.get(_currentUser);
            if (currentuserEvents != null) {
                for (int i = 0; i < currentuserEvents.size(); i++) {
                    Event e = currentuserEvents.get(i);
                    if (e.getEventDate().equals(currentDate)) {
                        if (j >= 5) {
                            break;
                        }
                        _upcomingEventsModel.setValueAt(e.getEventName() + " at " + e.getEventTime(), j, 0);
                        j++;
                    }
                }
            }
        }
        if (_currentUser != null) { // null check should be removed later
            ArrayList<Event> currentuserEvents = _userInfo.get(_currentUser);
            if (currentuserEvents != null) {
                for (int i = 0; i < currentuserEvents.size(); i++) {
                    Event e = currentuserEvents.get(i);
                    System.out.println("event date is " + e.getEventDate());
                }
            }
        }
    }
    
    private void hideNonAdmin() {
        mnuAddUser.setVisible(false);
        mnuListEditUser.setVisible(false);
        mnuRemoveUser.setVisible(false);
        mnuServerLocation.setVisible(false);
    }
    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        try {
            new Logon().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }//GEN-LAST:event_btnLogoutActionPerformed

    private void mnuRemoveUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRemoveUserActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        RemoveUser.run();
    }//GEN-LAST:event_mnuRemoveUserActionPerformed

    private void mnuListEditUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuListEditUserActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        EditUser.run();
    }//GEN-LAST:event_mnuListEditUserActionPerformed

    private void mnuUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuUserActionPerformed

    private void mnuServerLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuServerLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuServerLocationActionPerformed

    private void cmbYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbYearActionPerformed
        // TODO add your handling code here:
        if (cmbYear.getSelectedItem() != null) {
            String cYear = cmbYear.getSelectedItem().toString();
            _currentYear = Integer.parseInt(cYear);
            refreshCalendar(_currentMonth, _currentYear);
        }

    }//GEN-LAST:event_cmbYearActionPerformed
    
    public static void refreshCalendar(int month, int year) {
        String[] months = {"January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"};
        int numDays, startMonth;
        
        btnPrev.setEnabled(true);
        btnNext.setEnabled(true);

        // to avoid going over years we allow
        if (month == 11 && year >= _realYear + 100) {
            btnNext.setEnabled(false);
        }
        if (month == 0 && year <= _realYear - 100) {
            btnPrev.setEnabled(false);
        }
        
        lblMonth.setText(months[month] + " " + _currentYear);
        cmbYear.setSelectedItem(String.valueOf(year));
        for (int i = 0; i < 6; i++) {
            for (int j = 0; j < 7; j++) {
                _CalendarTableModel.setValueAt(null, i, j);
            }
        }
        
        GregorianCalendar calendar = new GregorianCalendar(year, month, 1);
        numDays = calendar.getActualMaximum(GregorianCalendar.DAY_OF_MONTH);
        startMonth = calendar.get(GregorianCalendar.DAY_OF_WEEK);
        
        for (int i = 1; i <= numDays; i++) {
            int row = (i + startMonth - 2) / 7;
            int column = (i + startMonth - 2) % 7;
            _CalendarTableModel.setValueAt(i, row, column);
            //tblCalendar.setValueAt(String.valueOf(i)+"\ndata", row, column);
        }
        tblCalendar.setDefaultRenderer(tblCalendar.getColumnClass(0), new tblCalendarRenderer());
    }
    
    static class tblCalendarRenderer extends DefaultTableCellRenderer {
        
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean selected, boolean focused, int row, int column) {
            super.getTableCellRendererComponent(table, value, selected, focused, row, column);
            if (column == 0 || column == 6) { // weekend
                setBackground(new Color(255, 220, 220));
            } else {
                setBackground(new Color(255, 255, 255));
            }
            if (value != null) {
                if (Integer.parseInt(value.toString()) == _realDay && _currentMonth == _realMonth && _currentYear == _realYear) {
                    //current Day
                    setBackground(new Color(220, 220, 255));
                }
            }
            
            if (selected) {
                setBackground(new Color(128, 128, 128));
                Object dateChosen = _CalendarTableModel.getValueAt(tblCalendar.getSelectedRow(),
                        tblCalendar.getSelectedColumn());
                _eventday = String.valueOf(dateChosen);
                //printing for debug purposes
                System.out.println("date is " + _currentMonth + "-" + _eventday + "-" + _currentYear);
            }
            
            Color color = Color.black;
            MatteBorder border = new MatteBorder(1, 1, 0, 0, color);
            setBorder(border);
            setForeground(Color.black);
            setSize(table.getColumnModel().getColumn(column).getWidth(),
                    Short.MAX_VALUE);
            return this;
        }
    }
    private void btnPrevMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrevMouseClicked
        // TODO add your handling code here:
        if (_currentMonth == 0) {
            _currentMonth = 11;
            _currentYear -= 1;
        } else {
            _currentMonth -= 1;
        }
        refreshCalendar(_currentMonth, _currentYear);
    }//GEN-LAST:event_btnPrevMouseClicked

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextMouseClicked
        // TODO add your handling code here:
        if (_currentMonth == 11) {
            _currentMonth = 0;
            _currentYear += 1; // go to next year
        } else {
            _currentMonth += 1; // just increment month
        }
        refreshCalendar(_currentMonth, _currentYear);
    }//GEN-LAST:event_btnNextMouseClicked

    private void cmbYearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbYearMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_cmbYearMouseClicked

    private void tblCalendarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCalendarMouseClicked
        buildDateGUI();
        jScrollPane1.setViewportView(dateGUI);
    }                                        
//GEN-LAST:event_tblCalendarMouseClicked

    //build the GUI to be displayed when a particular date in the calendar is clicked
        private void buildDateGUI() {
        dateGUI = new javax.swing.JPanel();
        javax.swing.JPanel upperPanel = new javax.swing.JPanel();
        javax.swing.JPanel lowerPanel = new javax.swing.JPanel();
        java.awt.GridLayout layout = new java.awt.GridLayout(0, 2);
        lowerPanel.setLayout(layout);
        
        javax.swing.JButton btnBack = new javax.swing.JButton("Back");
        javax.swing.JButton btnCreateEvent = new javax.swing.JButton("Create Event");
        
        upperPanel.add(btnBack);
        upperPanel.add(btnCreateEvent);
        lowerPanel.add(new javax.swing.JLabel("Time"));
        lowerPanel.add(new javax.swing.JLabel("Events"));
        dateGUI.add(upperPanel);
        dateGUI.add(lowerPanel);
        
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                jScrollPane1.setViewportView(tblCalendar);
            }
        });
       
        btnCreateEvent.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                jButton1ActionPerformed(e);
            }
        });
    }
    
    private void mnuEditPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEditPasswordActionPerformed
        // TODO add your handling code here:
        String newPassword = JOptionPane.showInputDialog("Enter new password here");
        if (_logged == true && !"".equals(newPassword)) {
            _currentUser.setPassword(newPassword);
            // _userInfo.put(_currentUser, _currentUser.isAdmin());
            Serialize.save(Serialize.fileLocation);
        }
    }//GEN-LAST:event_mnuEditPasswordActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        print();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void mnuCustomizeCalendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCustomizeCalendarActionPerformed
        // TODO add your handling code here:
        Color c = JColorChooser.showDialog(null, "Select Color", pnlBackground.getBackground());
        if (c != null) {
            pnlBackground.setBackground(c);
            _currentUser.setCustomecolor(c);
            Serialize.save(Serialize.fileLocation);
        }
        jDialog1.setVisible(true);
    }//GEN-LAST:event_mnuCustomizeCalendarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CreateEvent.run();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnEditUser_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditUser_CancelActionPerformed
        editUser_Box.dispose();
    }//GEN-LAST:event_btnEditUser_CancelActionPerformed

    private void btnEditUser_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditUser_SaveActionPerformed
        EditUser._edit.setUsername(txtEditUser_Username.getText());
        EditUser._edit.setEmail(txtEditUser_Email.getText());
        String password = txtEditUser_Pwd.getText();
        String confPassword = txtEditUser_Pwd2.getText();
        if (tglEditUser_Admin.isSelected() == true) {
            EditUser._edit.makeAdmin(true);
        } else {
            EditUser._edit.makeAdmin(false);
        }
        if (!password.equals(confPassword)) {
            JOptionPane.showMessageDialog(null, "Password did not match", "Password Mismatch", JOptionPane.ERROR_MESSAGE);
        } else {
        
        Serialize.save(Serialize.fileLocation);
        JOptionPane.showMessageDialog(null, "User "+EditUser._edit.getUsername()+ " has been edited. Changes saved.");
        editUser_Box.dispose();
        EditUser.listUsers();
        }
    }//GEN-LAST:event_btnEditUser_SaveActionPerformed
    
    private void print() {
        try {
            tblCalendar.print();
        } catch (PrinterException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     */
    public static void run() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new GUI().setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnEditUser_Cancel;
    public javax.swing.JButton btnEditUser_Save;
    private javax.swing.JButton btnLogout;
    private static javax.swing.JButton btnNext;
    private static javax.swing.JButton btnPrev;
    private static javax.swing.JComboBox<String> cmbYear;
    public static javax.swing.JDialog editUser_Box;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JDialog jDialog1;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private static javax.swing.JLabel lblMonth;
    private javax.swing.JMenuItem mnuAddUser;
    private javax.swing.JMenuItem mnuCustomizeCalendar;
    private javax.swing.JMenuItem mnuEditPassword;
    private javax.swing.JMenuItem mnuExit;
    private javax.swing.JMenuItem mnuListEditUser;
    private javax.swing.JMenu mnuMainEdit;
    private javax.swing.JMenuItem mnuRemoveUser;
    private javax.swing.JMenuItem mnuServerLocation;
    private javax.swing.JMenu mnuUser;
    private javax.swing.JPanel pnlBackground;
    private static javax.swing.JTable tblCalendar;
    private static javax.swing.JTable tblUpcomingEvents;
    public static javax.swing.JToggleButton tglEditUser_Admin;
    public static javax.swing.JTextField txtEditUser_Email;
    public static javax.swing.JPasswordField txtEditUser_Pwd;
    public static javax.swing.JPasswordField txtEditUser_Pwd2;
    public static javax.swing.JTextField txtEditUser_Username;
    // End of variables declaration//GEN-END:variables
    private javax.swing.JPanel dateGUI;
}
